name: bookapps
description: Biblioteca personal con Firebase Auth, Google Sign-In y Firestore. Desarrollado por Jonathan Santos.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.1
  firebase_storage: ^12.4.10
  flutter_svg: ^2.0.7
  provider: ^6.1.5
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.0.0
  uuid: ^4.3.3
  epub_view: ^3.2.0
  file_picker: ^10.2.0
  pdfx: ^2.6.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.1 # <-- para cachear portadas de libros e imágenes de usuario
  mime: ^2.0.0
  universal_file: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png

